# Mozilla User Preferences

/* Do not edit this file.
 *
 * If you make changes to this file while the application is running,
 * the changes will be overwritten when the application exits.
 *
 * To make a manual change to preferences, you can visit the URL about:config
 */

user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1463611422);
user_pref("app.update.lastUpdateTime.background-update-timer", 1463611058);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 1463611542);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1463611179);
user_pref("app.update.lastUpdateTime.experiments-update-timer", 1463611302);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1463608285);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 1463611662);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.cache.disk.capacity", 358400);
user_pref("browser.cache.disk.filesystem_reported", 1);
user_pref("browser.cache.disk.smart_size.first_run", false);
user_pref("browser.cache.frecency_experiment", 3);
user_pref("browser.download.importedFromSqlite", true);
user_pref("browser.migration.version", 30);
user_pref("browser.newtabpage.enhanced", true);
user_pref("browser.newtabpage.introShown", true);
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.places.smartBookmarksVersion", 7);
user_pref("browser.reader.detectedFirstArticle", true);
user_pref("browser.rights.3.shown", true);
user_pref("browser.search.countryCode", "US");
user_pref("browser.search.region", "US");
user_pref("browser.sessionstore.upgradeBackup.latestBuildID", "20150826023504");
user_pref("browser.slowStartup.averageTime", 0);
user_pref("browser.slowStartup.samples", 0);
user_pref("browser.startup.homepage_override.buildID", "20150826023504");
user_pref("browser.startup.homepage_override.mstone", "40.0.3");
user_pref("browser.syncPromoViewsLeftMap", "{\"addons\":3,\"bookmarks\":4}");
user_pref("browser.toolbarbuttons.introduced.pocket-button", true);
user_pref("browser.uiCustomization.state", "{\"placements\":{\"PanelUI-contents\":[\"edit-controls\",\"zoom-controls\",\"new-window-button\",\"privatebrowsing-button\",\"save-page-button\",\"print-button\",\"history-panelmenu\",\"fullscreen-button\",\"find-button\",\"preferences-button\",\"add-ons-button\",\"developer-button\"],\"addon-bar\":[\"addonbar-closebutton\",\"status-bar\"],\"PersonalToolbar\":[\"personal-bookmarks\"],\"nav-bar\":[\"urlbar-container\",\"search-container\",\"bookmarks-menu-button\",\"pocket-button\",\"downloads-button\",\"home-button\",\"loop-button\",\"abp-toolbarbutton\"],\"TabsToolbar\":[\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\"]},\"seen\":[\"abp-toolbarbutton\"],\"dirtyAreaCache\":[\"PersonalToolbar\",\"nav-bar\",\"TabsToolbar\",\"PanelUI-contents\",\"addon-bar\"],\"currentVersion\":4,\"newElementCount\":0}");
user_pref("datareporting.healthreport.lastDataSubmissionRequestedTime", "1463608222085");
user_pref("datareporting.healthreport.lastDataSubmissionSuccessfulTime", "1463608222615");
user_pref("datareporting.healthreport.nextDataSubmissionTime", "1463694622615");
user_pref("datareporting.healthreport.service.firstRun", true);
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1463544545361");
user_pref("datareporting.policy.firstRunTime", "1463504251793");
user_pref("datareporting.sessions.current.activeTicks", 12);
user_pref("datareporting.sessions.current.firstPaint", 999);
user_pref("datareporting.sessions.current.main", 39);
user_pref("datareporting.sessions.current.sessionRestored", 1133);
user_pref("datareporting.sessions.current.startTime", "1463612146536");
user_pref("datareporting.sessions.current.totalTime", 264);
user_pref("datareporting.sessions.currentIndex", 4);
user_pref("datareporting.sessions.previous.2", "{\"s\":1463608158386,\"a\":8,\"t\":176,\"c\":true,\"m\":218,\"fp\":1419,\"sr\":1715}");
user_pref("datareporting.sessions.previous.3", "{\"s\":1463610937511,\"a\":54,\"t\":1205,\"c\":true,\"m\":48,\"fp\":887,\"sr\":1211}");
user_pref("datareporting.sessions.prunedIndex", 1);
user_pref("dom.apps.reset-permissions", true);
user_pref("dom.mozApps.used", true);
user_pref("experiments.activeExperiment", false);
user_pref("extensions.adblockplus.currentVersion", "2.7.3");
user_pref("extensions.adblockplus.notificationdata", "{\"lastCheck\":1463612206731,\"softExpiration\":1463703841839,\"hardExpiration\":1463781019634,\"data\":{\"notifications\":[],\"version\":\"201605182149\"},\"lastError\":0,\"downloadStatus\":\"synchronize_ok\",\"downloadCount\":2}");
user_pref("extensions.blocklist.pingCountTotal", 3);
user_pref("extensions.blocklist.pingCountVersion", 3);
user_pref("extensions.bootstrappedAddons", "{\"{d10d0bf8-f5b5-c8b4-a8b2-2b9879e08c5d}\":{\"version\":\"2.7.3\",\"type\":\"extension\",\"descriptor\":\"/Users/lkloh/Library/Application Support/Firefox/Profiles/r0sux2ly.default/extensions/{d10d0bf8-f5b5-c8b4-a8b2-2b9879e08c5d}.xpi\",\"multiprocessCompatible\":false}}");
user_pref("extensions.databaseSchema", 17);
user_pref("extensions.enabledAddons", "%7B972ce4c6-7e08-4474-a285-3208198ce6fd%7D:40.0.3");
user_pref("extensions.getAddons.cache.lastUpdate", 1463611429);
user_pref("extensions.getAddons.databaseSchema", 5);
user_pref("extensions.hotfix.lastVersion", "20160128.01");
user_pref("extensions.lastAppVersion", "40.0.3");
user_pref("extensions.lastPlatformVersion", "40.0.3");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.shownSelectionUI", true);
user_pref("extensions.xpiState", "{\"app-profile\":{\"{d10d0bf8-f5b5-c8b4-a8b2-2b9879e08c5d}\":{\"d\":\"/Users/lkloh/Library/Application Support/Firefox/Profiles/r0sux2ly.default/extensions/{d10d0bf8-f5b5-c8b4-a8b2-2b9879e08c5d}.xpi\",\"e\":true,\"v\":\"2.7.3\",\"st\":1463611566000}},\"app-global\":{\"{972ce4c6-7e08-4474-a285-3208198ce6fd}\":{\"d\":\"/Applications/Firefox.app/Contents/Resources/browser/extensions/{972ce4c6-7e08-4474-a285-3208198ce6fd}\",\"e\":true,\"v\":\"40.0.3\",\"st\":1440587589000,\"mt\":1440584978000}}}");
user_pref("gecko.buildID", "20150826023504");
user_pref("gecko.mstone", "40.0.3");
user_pref("gfx.blacklist.direct2d", 3);
user_pref("gfx.blacklist.hardwarevideodecoding", 3);
user_pref("idle.lastDailyNotification", 1463504688);
user_pref("media.gmp-gmpopenh264.lastUpdate", 1463504882);
user_pref("media.gmp-gmpopenh264.version", "1.5.3");
user_pref("media.gmp-manager.buildID", "20150826023504");
user_pref("media.gmp-manager.lastCheck", 1463608226);
user_pref("network.cookie.prefsMigrated", true);
user_pref("network.predictor.cleaned-up", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("pdfjs.previousHandler.alwaysAskBeforeHandling", true);
user_pref("pdfjs.previousHandler.preferredAction", 4);
user_pref("places.database.lastMaintenance", 1463504688);
user_pref("places.history.expiration.transient_current_max_pages", 104858);
user_pref("plugin.disable_full_page_plugin_for_types", "application/pdf");
user_pref("plugin.importedState", true);
user_pref("privacy.sanitize.migrateClearSavedPwdsOnExit", true);
user_pref("privacy.sanitize.migrateFx3Prefs", true);
user_pref("signon.importedFromSqlite", true);
user_pref("storage.vacuum.last.index", 0);
user_pref("storage.vacuum.last.places.sqlite", 1463504688);
user_pref("toolkit.startup.last_success", 1463612146);
